# Generated by Django 2.2.28 on 2022-10-20 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del director', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo de la pelicula', max_length=200)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.Director')),
            ],
        ),
        migrations.DeleteModel(
            name='Peliculas',
        ),
    ]
