# Generated by Django 2.2.28 on 2022-10-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_auto_20221020_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del genero', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='resumen',
            field=models.TextField(help_text='Titulo de la pelicula', null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.ManyToManyField(to='peliculas.Genero'),
        ),
    ]
