# Generated by Django 2.2.28 on 2022-11-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_auto_20221020_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='fecha',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
