# Generated by Django 2.2.28 on 2022-11-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_pelicula_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fecha',
            field=models.DateField(help_text='Fecha de la pelicula', null=True),
        ),
    ]
